import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 🎥 Responsive Background Video for All Devices */}
        <video
          autoPlay
          muted
          loop
          playsInline
          preload="auto"
          className="fixed top-0 left-0 w-full h-full object-cover pointer-events-none z-[-1]"
        >
          <source
            src="/assets/DESKTOP.mp4"
            type="video/mp4"
            media="(min-width: 1024px)"
          />
          <source
            src="/assets/TABLET.mp4"
            type="video/mp4"
            media="(min-width: 640px)"
          />
          <source
            src="/assets/MOBILE.mp4"
            type="video/mp4"
            media="(max-width: 639px)"
          />
          Your browser does not support the video tag.
        </video>

        {children}
      </body>
    </html>
  );
}
